version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.40.3
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: hugo -v
      - run:
          name: "Test Website"
          command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore
      - deploy:
          command: ./deploy.sh
